### ISSUE TITLE
Increase info button tap target size

### ISSUE THREAD

**Issue by cg433n** [ualibraries/ual-libcal#17]

**Comment by smayden** [comment]
The new info button overhangs the table cell on small screens (actually the old one did too)

![info button](https://user-images.githubusercontent.com/10873398/27610853-df6a39ee-5b44-11e7-9879-c26d84e7057e.PNG)

**Comment by smayden** [comment]
Also there is another screen still showing the old info button (the search room reservation screen)

![info-button-2](https://user-images.githubusercontent.com/10873398/27611609-b325867e-5b47-11e7-8543-0fb84881dac5.PNG)
