### ISSUE TITLE
Under 'Booking Details', hide 'Add Equipment' button

### ISSUE THREAD

**Issue by cg433n** [ualibraries/ual-libcal#21]

**Comment by smayden** [comment]
We need to verify with AIS that we actually want to do this. I'm confused about why it is showing for only some room types, so it is probably easy to remove in the configuration

**Comment by smayden** [comment]
I talked with Mona and Rachel about this today and they confirmed that we do want to hide the Add Equipment buttons. Slaven previously gave Rachel code to do this and she included it for one room type, but we'll have to do it for all of them. Unless there is a global approach that is easier. We may need to bring this button back later on when we add in equipment lending

**Comment by smayden** [comment]
The add equipment button is still showing on all room types except Main group study rooms. I currently see it on: 
![add-equipment](https://user-images.githubusercontent.com/10873398/27597313-d9364cda-5b16-11e7-8453-28656a481d3b.PNG)

•	Main collaboration
•	Main technology group study
•	SEL group study (screen shot)
•	SEL collaboration
•	SEL Technology group study
•	SEL Faculty collaborative room
•	HSL group study
•	HSL collaboration
•	Fine Arts group study
