### ISSUE TITLE
Room info modals are not responsive

### ISSUE THREAD

**Issue by cg433n** [ualibraries/ual-libcal#30]
Don't forget to check images

**Comment by smayden** [comment]
They are now broken (and tiny) on desktop.
![tiny-room](https://user-images.githubusercontent.com/10873398/27557839-e75c68e6-5a6f-11e7-85f4-f6d50eddab14.PNG)

**Comment by cg433n** [comment]
We need to change the room info modal grid from 4/8 to 5/7
