### ISSUE TITLE
Take new photos of rooms to include in LibCal

### ISSUE THREAD

**Issue by cg433n** [ualibraries/ual-libcal#33]

**Comment by smayden** [comment]
I don't think there is any design work for this. We confirmed in our meeting that the images are currently small because that was what was uploaded. We need to take new/better photos and re-upload.

**Comment by smayden** [comment]
Cameron is working on taking photos for this

**Comment by smayden** [comment]
Cameron did photos for all rooms at HSL, Main, SEL, and Fine Arts!
