### ISSUE TITLE
Show current date instead of date span on calendar page

### ISSUE THREAD

**Issue by cg433n** [ualibraries/ual-libcal#35]

**Comment by smayden** [comment]
And why do some of our locations/categories do a 5-day span? Either way one day would be the most usable.

![libcal-fine-arts-5day-span](https://user-images.githubusercontent.com/10873398/28143108-d2a3b0ac-6718-11e7-8819-a63fb5c4563c.PNG)

**Comment by smayden** [comment]
I don't see any changes to this on the LibCal staging site (the calendar still shows a multi-day span). Is there a setting somewhere to change this? If you use the forward arrow instead of advancing one day, it advances to the start of the next 3 day span (or 5 or 6 days on some rooms/sites).

**Comment by smayden** [comment]
From Slaven: 

"There is now a setting to toggle the system between dynamically determining how many days to show, or always showing a single day (Admin > Equipment & Spaces > Settings > Public Spaces Settings)."

I can now see this option on the staging server. Yay!
