### ISSUE TITLE
Update room availability colors

### ISSUE THREAD

**Issue by cg433n** [ualibraries/ual-libcal#41]

**Comment by RuiQiDev** [comment]
Green in table: 67D199
Green in "available" button: 58C189
Blue in table and in "Your selecting" button are the same: 2483bb
Light grey in table: E5E5E5
Light grey in "Unavailable" button: CDCDCD

**Comment by smayden** [comment]
We had feedback in our design review that the contrast of "Unavailable" with the gray color was still an issue.
