### ISSUE TITLE
Add 'Make new reservation' button to reservation cancelation page

### ISSUE THREAD

**Issue by cg433n** [ualibraries/ual-libcal#44]
Add a button to the reservation cancelation page titled: "Make a new reservation" which takes the user to the default spaces page.

**Comment by smayden** [comment]
This was closed but I do not see it on the site.

![cancel screen](https://user-images.githubusercontent.com/10873398/27890172-daefae64-61a5-11e7-8552-e0118bc7ae45.PNG)

**Comment by cg433n** [comment]
Unable to replicate.
