### ISSUE TITLE
Add header

### ISSUE THREAD

**Issue by cg433n** [ualibraries/ual-libcal#5]
We want to use the header from LibGuides (http://libguides.library.arizona.edu/ABE501-ResearchMethods)

<img width="1189" alt="screen shot 2017-06-19 at 11 52 08 am" src="https://user-images.githubusercontent.com/868735/27300787-c48ee1ca-54e5-11e7-9e64-004bf97aaaae.png">
User story #1

**Comment by smayden** [comment]
The header looks good, but I notice that the white space at the bottom of the "A" is missing. 

![libcal header](https://user-images.githubusercontent.com/10873398/27409889-bb4a18b4-5698-11e7-93e4-31f58ce42803.PNG)
