### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by cg433n** [ualibraries/ual-libcal#6]
We want to use the footer from LibGuides (http://libguides.library.arizona.edu/ABE501-ResearchMethods)

<img width="1228" alt="screen shot 2017-06-19 at 11 53 24 am" src="https://user-images.githubusercontent.com/868735/27300832-f14cca4c-54e5-11e7-98ac-b375dbd1b56b.png">

User story #1

**Comment by smayden** [comment]
Apologies for not realizing footer content on other springshare tools is out of date. We need a few updates to the links/content to match what is on new.library:

Remove "Tel" from the phone number and style: (520) 621-6442
Change Library Policies to just Policies and link should point to: http://new.library.arizona.edu/policies
Change Employment to Job opportunities and link should point to: http://new.library.arizona.edu/jobs

**Comment by smayden** [comment]
I see you updated the links, but "Employment" should be changed to "Job opportunities"
