### ISSUE TITLE
Can't customize "Submit Time Slots" button

### ISSUE THREAD

**Issue by blakistonr** [ualibraries/ual-libcal#67]
Right now it's "Sumbit Time slots" - change to "Submit time slots"

**Comment by blakistonr** [comment]
![case](https://user-images.githubusercontent.com/5722112/28276721-a24c2d00-6acc-11e7-9d65-3f31b13847a6.png)

**Comment by smayden** [comment]
We heard from Slaven that this (and most other issues) were fixed. I have not be able to verify it yet since this version of the button only appears once authentication is turned on.

**Comment by antf** [comment]
Hi, this button uses a language token from the 'Room Bookings' page, rather than the Equipment & Spaces section, so you can customize the text as it stands. However, preferably a new token needs to be created for Equipment & Spaces. I'll add it to the list! Thanks

**Comment by smayden** [comment]
Awesome! That did it!
