### ISSUE TITLE
Customization on confirmation screen not working

### ISSUE THREAD

**Issue by smayden** [ualibraries/ual-libcal#73]
I'm customizing the text users see on the confirmation screen about getting a confirmation email, but it does not show up.
![libcal-language-customization](https://user-images.githubusercontent.com/10873398/28588864-c5a4c964-7130-11e7-968c-722cc529aa97.PNG)

![libcal-confimation-text](https://user-images.githubusercontent.com/10873398/28588868-c8cf286e-7130-11e7-8671-87fde2241e9c.PNG)

**Comment by antf** [comment]
Hi, you're editing the wrong language token - you need to edit the first language token in the screenshot. 
Cheers,
Anthony

**Comment by smayden** [comment]
Sorry for that oversight Anthony, but thanks for letting us know!
